---
galaxy_info:
  author: Alexey Medvedchikov
  description: An ansible role for RabbitMQ cluster
  company: 2GIS, LLC
  license: LGPL
  min_ansible_version: 1.3
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - squeeze
    - wheezy
  categories:
  - clustering
dependencies: []
