---
# Configure RabbitMQ

- name: rabbitmq config file
  template: src=etc/rabbitmq/rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config owner=root group=root mode=0644
  notify: restart rabbitmq-server
  tags: [configuration,rabbitmq]

- name: rabbitmq default file
  template: src=etc/default/rabbitmq-server.j2 dest=/etc/default/rabbitmq-server owner=root group=root mode=0644
  notify: restart rabbitmq-server
  tags: [configuration,rabbitmq]

- name: rabbitmq environment variables
  template: src=etc/rabbitmq/rabbitmq-env.j2 dest=/etc/rabbitmq/rabbitmq-env.conf owner=root group=root mode=0644
  notify: restart rabbitmq-server
  tags: [configuration,rabbitmq]   
