---
# Configure RabbitMQ for cluster

- name: backup old erlang cookie
  shell: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
  tags: [configuration,rabbitmq]
  when: ansible_os_family == "Debian"

- name: check if erlang cookie changed and if it is so stopping server
  template: src=erlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie.old owner=rabbitmq group=rabbitmq mode=0400
  notify: stop rabbitmq-server
  tags: [configuration,rabbitmq]
  when: ansible_os_family == "Debian"

- meta: flush_handlers

- name: updating rabbitmq erlang cookie
  template: src=erlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400
  tags: [configuration,rabbitmq]

- name: remove old erlang cookie
  file: path=/var/lib/rabbitmq/.erlang.cookie.old state=absent
  tags: [configuration,rabbitmq]
